source 'https://github.com/CocoaPods/Specs.git'

platform :ios, 7.0


target 'OnlineVideoClient', :exclusive => true do

  pod 'AsyncDisplayKit'

  pod 'Reveal-iOS-SDK'
  pod 'pop'
  pod 'SDWebImage'
  pod 'parse'

  pod 'Regexer'
  pod 'SWRevealViewController'
  pod 'AFNetworking'

  pod 'ISMemoryCache'
  pod 'EGOCache'
  pod 'ASImageResize'
  pod 'XMLDictionary'
  pod 'ABSQLite'

  pod 'Shimmer'
  pod 'TCBlobDownload'

  # ________________open projects___________________
  pod "JZGGTabBar", :path => "../dependencies/lib/JZGGTabBar"
  pod "YKMediaPlayerKit", :path => "../dependencies/lib/YKMediaPlayerKit"
  pod "MPMoviePlayerController-Subtitles", :path => "../dependencies/lib/MPMoviePlayerController-Subtitles"

  pod "KRLCollectionViewGridLayout", :path => "../dependencies/lib/KRLCollectionViewGridLayout"

  # ________________collect common library___________________
  pod "IOS_Collection_Code", :path => "../dependencies/collect/IOS_Collection_Code"

  # ________________Project layers___________________
  pod "Business-Logic-Layer", :path => "../dependencies/layers/Business-Logic-Layer"
  pod "google-api-services-youtube", :path => "../dependencies/layers/google-api-services-youtube"

  # ________________Projects for iPad___________________
  # ________________module Projects___________________
  pod "VideoWatchDetailViewControlleriPad", :path => "../dependencies/ipad/VideoWatchDetailViewControlleriPad"
  pod "Youtube_ChannelPage_Controller", :path => "../dependencies/ipad/Youtube_ChannelPage_Controller"
  pod "youtube_slide_menu", :path => "../dependencies/ipad/youtube_slide_menu"
  pod "YoutubeCollectionView", :path => "../dependencies/ipad/YoutubeCollectionView"
  pod "Movie_subtitle_manager", :path => "../dependencies/ipad/Movie_subtitle_manager"

  pod 'media_sqlite_manager', :path => '../dependencies/server/media_sqlite_manager'
  pod 'app_cofigure_manager', :path => '../dependencies/server/app_cofigure_manager'


end

target 'OnlineVideoClientTests', :exclusive => true do

  # pod 'OCMockito', '~> 1.0'
  pod 'media_sqlite_manager', :path => '../dependencies/server/media_sqlite_manager'

end
